version: "3.8"

services:
  server:
    container_name: image-uploader-server
    restart: unless-stopped
    image: server-image-uploader:1.0.0
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - NODE_ENV=development
      - API_PORT=5000
    volumes:
      - "./server/src:/app/src"
    command: "npm run dev"
  client:
    container_name: image-uploader-client
    restart: unless-stopped
    image: client-image-uploader:1.0.0
    depends_on:
      - server
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    environment:
      - NODE_ENV=development
      - FRONTEND_PORT=5173
      - VITE_API_URL=http://localhost:5000
    volumes:
      - "./client/src:/app/src"
    command: "npm run dev:docker"